completed 4.2
Abdul18712/freyr-intro pull request #4
Opened 2023-12-27 21:07 UTC by Abdul18712

2023-12-28 20:10 UTC, gsvidal requested changes
I suggested you some changes.

2023-12-28 20:10 UTC, gsvidal commented on js/index.js
> +footer.appendChild(copyright);
So in this section you need to make some fixes:

First you'll get null when trying to make a reference to an element that doesn't exist in the document.
In line 6 you're getting an error related to that because there's no element with an id="copyright", you could create it above that line with the `setAttribute` method.

After that you'll also need to append the copyright item to some element in the document, otherwise you'll get the same error because you can modify the innerHTML of an element that doesn't exist in the document.

2023-12-28 20:10 UTC, gsvidal commented on js/index.js
> +}
Currently you're not getting any skill rendered in the browser, because you're having a reference error (array is not defined), in line 13 that array is not define and is not required at all, you can delete the whole line 13.

You can also change in line 14 the var skill variable for const skill, since is not changing in any iteration of the for loop.

2023-12-28 20:10 UTC, gsvidal commented on index.html
> +
You can delete the double quotes in the h2 content.

2023-12-29 01:27 UTC, Abdul18712 commented on js/index.js
> +footer.appendChild(copyright);
shouldnt the create element method make a 'p' method in the footer, then the copy right is connected to it

2023-12-29 01:28 UTC, Abdul18712 commented on js/index.js
> +footer.appendChild(copyright);
![image](https://github.com/Abdul18712/freyr-intro/assets/110927627/74d3c07f-74f7-469f-af6f-915bc3896c20)

2023-12-29 02:02 UTC, Abdul18712 commented on js/index.js
> +}
done

2023-12-29 02:02 UTC, Abdul18712 commented on index.html
> +
done

2023-12-29 02:12 UTC, gsvidal commented on js/index.js
> +footer.appendChild(copyright);
Well other way would be accesing the innerHTML of the `copyright` variable itself (that's already making reference to the paragraph element) like `copyright.innerHTML`

2023-12-29 03:05 UTC, merged